// 接線復原／重做：真滑鼠與快捷鍵，不用掛鉤修改實驗台。
import fs from 'node:fs/promises';
import { openApp, Check } from './lib.mjs';

export async function run() {
  const T = new Check('接線復原／重做');
  const ui = await openApp(), p = ui.page;
  const snap = () => ui.snap('bench');
  const state = async () => (await snap()).history;
  const undo = () => p.click('[data-history="undo"]');
  const redo = () => p.click('[data-history="redo"]');
  const fixedPlug = async (lead, node) => { await p.click(`[data-lead="${lead}"]`); await p.click(`[data-node="${node}"]`); };
  const bbPlug = async (lead, hole) => { await p.click(`[data-lead="${lead}"]`); await p.click(`[data-hole="${hole}"]`); };
  const upload = async (content) => {
    const chooser = p.waitForEvent('filechooser');
    await p.click('[data-session="import"]');
    await (await chooser).setFiles({ name: 'undo-experiment.json', mimeType: 'application/json', buffer: Buffer.from(content) });
  };
  try {
    await ui.tab('bench');
    T.ok(await p.locator('[data-history="undo"]').isDisabled() && await p.locator('[data-history="redo"]').isDisabled(), '初始兩個按鈕停用');
    await p.click('[data-lead="AFG.CH1+"]');
    T.ok((await state()).undo === 0, '只選取導線不入歷史');
    await p.click('[data-node="A"]');
    T.ok((await state()).undo === 1 && (await snap()).wires['AFG.CH1+'] === 'A', '接上一條線記一步');
    await undo();
    T.ok(!(await snap()).wires['AFG.CH1+'] && (await state()).redo === 1, '復原拔掉線並啟用重做');
    await redo();
    T.ok((await snap()).wires['AFG.CH1+'] === 'A', '重做重新接到 A');
    await p.click('[data-lead="AFG.CH1+"]'); await p.click('[data-lead="AFG.CH1+"]');
    await undo();
    T.ok((await snap()).wires['AFG.CH1+'] === 'A', '固定板雙點拔線可以復原');
    await fixedPlug('AFG.CH1+', 'B');
    await undo();
    T.ok((await snap()).wires['AFG.CH1+'] === 'A', '導線移到 B 後可復原到 A');
    await fixedPlug('AFG.CH2+', 'G');
    T.ok((await state()).redo === 0 && await p.locator('[data-history="redo"]').isDisabled(), '新編輯清掉重做');
    const beforeDemo = (await snap()).wires, count = (await state()).undo;
    await p.click('[data-bench="demo"]');
    T.ok((await state()).undo === count + 1, '固定板示範整組接線只記一步');
    await undo();
    T.ok(JSON.stringify((await snap()).wires) === JSON.stringify(beforeDemo), '一次復原回示範前全部接線');
    await redo(); await p.click('[data-bench="clear"]'); await undo();
    T.ok(Object.keys((await snap()).wires).length === 8, '全部拔掉可一次復原');
    await p.selectOption('select[name="R"]', '4700');
    await p.selectOption('select[name="topo"]', 'CR');
    await p.locator('[data-node="A"]').focus();
    await p.keyboard.press('Control+z');
    T.ok((await snap()).topo === 'RC' && (await snap()).R === 4700, 'Ctrl Z 復原固定板接法');
    await p.keyboard.press('Control+Shift+z');
    T.ok((await snap()).topo === 'CR', 'Ctrl Shift Z 重做固定板接法');
    await p.selectOption('select[name="R"]', '10000');
    await p.locator('select[name="R"]').focus();
    const protectedCount = (await state()).undo;
    await p.keyboard.press('Meta+z');
    T.ok((await state()).undo === protectedCount && (await snap()).R === 10000, '選單內的 ⌘ Z 不攔截成接線復原');

    await p.check('input[name="board"][value="bb"]');
    T.ok((await state()).undo === 0, '麵包板與固定板歷史分開');
    await p.check('input[name="bbtool"][value="R"]');
    await p.click('[data-hole="a1"]');
    T.ok((await state()).undo === 0, '第一隻腳尚未完成，不入歷史');
    await p.click('[data-hole="a5"]');
    const original = (await snap()).bb.parts[0].stateId;
    T.ok((await state()).undo === 1 && (await snap()).bb.parts.length === 1, '擺完整元件記一步');
    await p.click('[data-hole="a1"]');
    T.ok((await state()).undo === 1 && (await ui.hint()).includes('已經插了'), '佔用孔拒絕，不入歷史');
    await p.check('input[name="bbtool"][value="select"]');
    await p.locator('[data-comp="R1"] > g rect').first().click();
    await p.selectOption('select[name="bbVal"]', '4700');
    await p.locator('[data-hole="a2"]').focus();
    await p.keyboard.press('Meta+z');
    T.ok((await snap()).bb.parts[0].value === 1000 && (await snap()).bb.parts[0].stateId === original, '⌘ Z 復原元件值，保留同一生命週期');
    await p.keyboard.press('Meta+Shift+z');
    T.ok((await snap()).bb.parts[0].value === 4700, '⌘ Shift Z 重做元件值');
    await bbPlug('DMM.I', 'b1');
    await bbPlug('DMM.LO', 'b5');
    T.ok((await snap()).bbWires['DMM.I'] === 'b1', '新增電流 I 端可接線');
    await undo();
    T.ok(!(await snap()).bbWires['DMM.LO'] && (await snap()).bbWires['DMM.I'] === 'b1', '電流導線接線也可逐步復原');
    await redo();
    await p.click('[data-lead="DMM.I"]'); await p.click('[data-lead="DMM.I"]');
    await undo();
    T.ok((await snap()).bbWires['DMM.I'] === 'b1', '麵包板雙點拔線可以復原');
    await p.check('input[name="bbtool"][value="select"]');
    await p.locator('[data-comp="R1"] > g rect').first().click();
    await p.keyboard.press('Delete');
    T.ok((await snap()).bb.parts.length === 0, 'Delete 刪除元件');
    await undo();
    T.ok((await snap()).bb.parts.length === 1 && (await snap()).bb.parts[0].stateId !== original, '復原刪除以新生命週期重新擺上元件');
    const keep = (await snap()).bb.parts.map(({ stateId, ...part }) => part);
    const beforeBBdemo = (await state()).undo;
    await p.click('[data-bb="demo-rc"]');
    T.ok((await state()).undo === beforeBBdemo + 1 && (await snap()).bb.parts.length === 2, '麵包板示範完整配置只記一步');
    await undo();
    T.ok(JSON.stringify((await snap()).bb.parts.map(({ stateId, ...part }) => part)) === JSON.stringify(keep), '麵包板示範可一次復原');
    const beforeCurrentDemo = (await state()).undo;
    await p.click('[data-bb="demo-current"]');
    T.ok((await state()).undo === beforeCurrentDemo + 1 && (await snap()).bbWires['DMM.I'] === 'i18'
      && (await ui.snap('dmm')).fn === 'DCI', '串接電流示範可發現，切到 DCI 且整組只記一步');
    await undo();
    T.ok((await snap()).bbWires['DMM.I'] === 'b1' && (await snap()).bb.parts[0].a === 'a1'
      && (await ui.snap('dmm')).fn === 'DCI', '復原電流示範恢復舊接線，保留目前儀器功能');
    await p.click('[data-bb="clear"]'); await undo();
    T.ok((await snap()).bb.parts.length === 1 && (await snap()).bbWires['DMM.I'] === 'b1', '清空麵包板可復原元件及導線');
    await p.check('input[name="board"][value="rc"]');
    T.ok((await snap()).R === 10000 && (await state()).undo === protectedCount, '切回固定板保留自己的配置與歷史');
    await p.click('[data-act="reset-one"]'); await undo();
    T.ok((await snap()).R === 10000 && (await snap()).topo === 'CR', '固定板重設可復原配置');
    await ui.tab('afg');
    await ui.press('AFG.KEY.OUTPUT');
    await ui.tab('bench'); await undo();
    T.ok((await ui.snap('afg')).ch[0].output === true, '接線復原保留後來的儀器設定');

    const historyBeforeBadFile = await state();
    await upload('{not json');
    await p.locator('.hintbar').filter({ hasText: '沒有載入實驗' }).waitFor();
    T.ok(JSON.stringify(await state()) === JSON.stringify(historyBeforeBadFile), '載入失敗保留復原／重做歷史');
    const downloading = p.waitForEvent('download');
    await p.click('[data-session="export"]');
    const download = await downloading;
    const file = await fs.readFile(await download.path(), 'utf8');
    await upload(file);
    await p.locator('.hintbar').filter({ hasText: '已載入實驗' }).waitFor();
    T.ok((await state()).undo === 0 && (await state()).redo === 0, '載入成功清掉固定板舊歷史');
    await p.check('input[name="board"][value="bb"]');
    T.ok((await state()).undo === 0 && (await state()).redo === 0, '載入成功也清掉麵包板舊歷史');
    await bbPlug('DMM.HI', 'c1');
    await p.locator('.save-status').filter({ hasText: '已自動保存' }).waitFor();
    await p.reload(); await p.locator('svg.bench-svg').waitFor();
    T.ok((await state()).undo === 0 && (await snap()).bbWires['DMM.HI'] === 'c1', '重新開啟保存配置，但不保存編輯歷史');
    await ui.shot('wiring-undo-redo');
    T.ok(ui.errors.length === 0, `沒有瀏覽器錯誤${ui.errors.length ? `：${ui.errors.join('; ')}` : ''}`);
  } finally { await ui.close(); }
  return T;
}
